reddit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('subreddit.urls', 'subreddit'), namespace='subreddit')),
]

subreddit/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.subreddit_view, name='index'),
    path('search/', views.search_view, name='search'),
    path('r/<sub_name>/', views.subreddit_view, name='subreddit'),
    re_path(r'r/(?P<sub_name>\w+)/(?P<sorted_by>\w+)/$', views.subreddit_view, name='subreddit'),
    path('r/<sub_name>/comments/<post_id>/', views.post_view, name='post'),
    re_path(r'r/(?P<sub_name>\w+)/comments/(?P<post_id>(\w|\d)+)/\w*/?$', views.post_view, name='post'),
    path('about/', views.about_view, name='about'),
]

templates/partials/comment.html
{% load subreddit_extras %}


{% for cmt in comments %}
  <div class="card {{ cmt.shadow }} {{ cmt.color }} mt-3">
    <div class="card-body text-wrap">

      <p>
        <a class="btn btn-dark rounded-circle {{ cmt.color }}" href="#comment-{{ cmt.id }}" data-toggle="collapse" aria-expanded="true">
          <i class="fa fa-minus-circle" aria-hidden="true"></i>
        </a>
        <a class="{{ cmt.op_color }} btn rounded" href="#">
          <b>{{ cmt.author_name }}</b>
        </a>
        {{ cmt.author_info }}
      </p>

      <div id="comment-{{ cmt.id }}" class="collapse gray-text">
        Content hidden
      </div>

      <div id="comment-{{ cmt.id }}" class="collapse show">
        {% autoescape off %}
          {{ cmt.body|safe }}
        {% endautoescape %}

        {% if cmt.replies %}
          {% include "partials/comment.html" with comments=cmt.replies %}
        {% endif %}
      </div>

    </div>
  </div>
{% endfor %}

templates/partials/comment_forloop.html
{% load subreddit_extras %}

{% instantiate post.comments.list as comments %}
{% for cmt in comments %}

  {% if color_switch %}
    {% instantiate "solarized-dark" as color_mode %}
  {% else %}
    {% instantiate "solarized-dark-2" as color_mode %}
  {% endif %}

  {% if top_level_comment %}
    {% instantiate "shadow" as shadow %}
  {% else %}
    {% instantiate "" as shadow %}
  {% endif %}

  {% instantiate cmt.author as cmt_author %}

  <div class="card {{ shadow }} {{ color_mode }} mt-3">
    <div class="card-body text-wrap">

      <p>
        <a class="btn btn-dark rounded-circle {{ color_mode }}" href="#comment-{{ cmt.id }}" data-toggle="collapse" aria-expanded="true">
          <i class="fa fa-minus-circle" aria-hidden="true"></i>
        </a>
        {% if cmt_author.name == post_author.name and post_author.name %}
          <a class="orange btn rounded" href="#">
            <b>{% parse_username cmt_author.name %}</b>
          </a>
        {% else %}
          <b>{% parse_username cmt_author.name %}</b>
        {% endif %}

        {% if cmt_author.name %}
          &nbsp;
          •
          &nbsp;
          {% parse_score cmt %}
          &nbsp;
          •
          &nbsp;
          {% post_age cmt %}
          {{ cmt.edited|yesno:"(edited)," }}
        {% endif %}
      </p>

      <div id="comment-{{ cmt.id }}" class="collapse gray-text">
        Content hidden
      </div>

      <div id="comment-{{ cmt.id }}" class="collapse show">
        {% autoescape off %}
          {% parse_body cmt.body_html as body %} 
          {{ body|safe }}
        {% endautoescape %}

        <!-- change_bool exists so that I can achieve the alternating colors for comment depths -->
      </div>

    </div>
  </div>
{% endfor %}

templates/partials/loading.html
{% load subreddit_extras %}

<div class="row justify-content-center loading d-none">
  <div class="spinner-border text-light" role="status">
    <span class="sr-only">Loading...</span>
  </div>
</div>

<script>
  var infinite = new Waypoint.Infinite({
    element: $('.infinite-container')[0],
    onBeforePageLoad: function () {
      $('.loading').toggleClass('d-none');
      $('.temp-link').addClass('d-none');
    },
    onAfterPageLoad: function ($items) {
      $('.loading').toggleClass('d-none');
    }
  });
</script>

templates/partials/post_card.html
{% load subreddit_extras %}

<div class="card shadow mb-3 solarized-dark">
  {% if post.embed %}
    <div class="embed-responsive embed-responsive-16by9 collapse media-embed" id="media-{{ post.id }}">
      {{ post.embed|safe }}
    </div>
  {% elif post.vid %}
    <div class="card-image collapse media-embed" id="media-{{ post.id }}">
      <div class="embed-responsive embed-responsive-16by9">
        <video preload="auto" controls="true" class="embed-responsive-item">
          <source src="{{ post.vid }}" type="video/mp4" />
        </video>
      </div>
    </div>
  {% elif post.img %}
    <div class="card-image solarized-dark collapse {{ post.show_media }} media-embed" id="media-{{ post.id }}" data-toggle="modal" data-target="#img-{{ post.id }}">
      <img class="card-img-top img-fluid" src="{{ post.img }}" alt="Image not found">
    </div>
  {% endif %}

  <div class="card-body">
    <div class="row">
      <div class="col">
        <h3 class="card-title">
          <a class="solarized-dark" href="{{ post.url }}">{{ post.title }}</a>
        </h3>
        <p class="card-text">
          {% if post.embed or post.vid or post.img or post.is_self and post.selftext %}
            <a class="blue btn btn-dark rounded-circle" data-toggle="collapse" href="#media-{{ post.id }}" aria-expanded="true">
              {% if post.is_self %}
                <i class="fas fa-file-alt"></i>
              {% else %}
                <i class="fas fa-play"></i>
              {% endif %}
            </a>
            &nbsp;
          {% endif %}
          <small>
            <a class="solarized-dark" href="{% url 'subreddit:subreddit' post.subreddit.display_name  %}">
              /r/{{ post.subreddit.display_name }}
            </a>
            &nbsp;
            •
            &nbsp;
            {{ post.age }}
            &nbsp;
            •
            &nbsp;
            {{ post.author_name }}
            &nbsp;
            •
            &nbsp;
            {{ post.content_origin }}
          </small>
        </p>

        {% if post.is_self and post.selftext %}
          <div class="collapse {{ post.show_selftext }} media-embed" id="media-{{ post.id }}">
            <p class="card-text">
              {% autoescape off %}
              {{ post.selftext_html|safe }}
              {% endautoescape %}
            </p>
          </div>
        {% endif %}
      </div>
      {% if not post.embed and "http" in post.thumbnail %}
        <div class="col-3 text-right">
          <img src="{{ post.thumbnail }}" alt="">
        </div>
      {% endif %}
    </div>
  </div>
  <div class="card-footer">
    <i class="fas fa-arrow-up"></i>
    &nbsp;
    <small>{{ post.score }} pts</small>  
    &nbsp;
    &nbsp;
    <a class="solarized-dark" href="{% url 'subreddit:post' post.subreddit.display_name post.id %}">
      <i class="fas fa-comments"></i>
      &nbsp;
      <small>{{ post.num_comments }} comments</small>
    </a>
  </div>

      <!-- <div class="card-footer">
        <i class="fas fa-arrow-up upvote"></i>
        &nbsp;
        &nbsp;
        <i class="fas fa-arrow-down downvote"></i>
        &nbsp;
        &nbsp;
        <i class="fas fa-ellipsis-v"></i>
        &nbsp;
        &nbsp;
        <a class="btn toggle-container solarized-dark-2" href="#">Toggle Container</a>
      </div> -->

</div>

{% if post.img %}
<div class="modal" id="img-{{ post.id }}">
  <div class="modal-dialog modal-dialog-centered modal-xl" data-toggle="modal" data-target="#img-{{ post.id }}">
    <div class="modal-content p-0">
        <div class="text-center">
          <img class="w-100 rounded" src="{{ post.img }}" alt="">
        </div>
    </div>
  </div>
</div>
{% endif %}

templates/partials/search_bar.html
{% load subreddit_extras %}

{% load crispy_forms_tags %}

<div class="card shadow solarized-dark mb-3">
  <div class="card-body">
    <form action="{% url 'subreddit:search' %}" method="post">
      {% csrf_token %}
      {{ search_field|crispy }}
    </form>
  </div>
</div>

templates/partials/sub_dropdown.html
{% load subreddit_extras %}


<div class="dropdown">
  <button class="orange btn btn-lg btn-dark dropdown-toggle" type="button" id="subreddit-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    {{ dropdown_label }}
  </button>
  <div class="dropdown-menu" aria-labelledby="subreddit-dropdown">
    <h6 class="dropdown-header">Subreddits</h6>
    <div class="dropdown-divider"></div>
    {% for sub in popular_subs %}
      <a class="dropdown-item" href="{% url 'subreddit:subreddit' sub.display_name  %}">{{ sub.display_name }}</a>
    {% endfor %}
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'subreddit:about' %}">About the Author</a>
  </div>
</div>

templates/partials/sub_sidebar.html
{% load subreddit_extras %}

<div class="card shadow solarized-dark mb-3">
  <div class="card-body">
    <h4 class="card-title">Popular Communities</h4>
    {% top_five popular_subs as five_subs %}
    {% for sub in five_subs %}
    <div class="card shadow solarized-dark-2 mt-3">
      <div class="card-body">
      <div class="row">
        <div class="col-3">
          {% if sub.icon_img %}
            <img src="{{ sub.icon_img }}" alt="" class="rounded-circle img-fluid p-2 orange">
          {% else %}
            <img src="/static/img/default_sub_icon.png" alt="" class="rounded-circle img-fluid p-2 orange">
          {% endif %}
        </div>
        <div class="col">
          <p class="card-text font-weight-bold">
            <a href="{% url 'subreddit:subreddit' sub.display_name %}">
              r/{{ sub.display_name }}
            </a>
          </p>
          <p class="card-text">{% num_with_comma sub.subscribers %} Subscribers</p>
        </div>
      </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

templates/partials/sub_sorting.html
{% load subreddit_extras %}

<div class="dropdown">
  <button class="btn green dropdown-toggle" type="button" id="sorting-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Sorting by: {{ sorted_by }}
  </button>
  <div class="dropdown-menu" aria-labelledby="sorting-dropdown">
    {% for st in sorting_types %}
    <a class="dropdown-item" href="{% url 'subreddit:subreddit' subreddit.display_name st %}">{{ st }}</a>
    {% endfor %}
  </div>
</div>

templates/partials/sub_sorting_links_from.html
{% load subreddit_extras %}

<div class="dropdown">
  <button class="btn magenta dropdown-toggle" type="button" id="subsorting-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Links from: {{ links_from_label }}
  </button>
  <div class="dropdown-menu" aria-labelledby="subsorting-dropdown">
    {% for si, label in sorting_intervals.items %}
    <a class="dropdown-item" href="{% url 'subreddit:subreddit' subreddit.display_name sorted_by %}?t={{ si }}">{{ label }}</a>
    {% endfor %}
  </div>
</div>